{
 "title": "UptimeLab Overview",
 "tags": [
  "uptimelab",
  "lab"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP requests (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[1m])) by (code, method)",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Request duration p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Process memory (bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_working_set_bytes", "legendFormat": "working set" }
   ]
  },
  {
   "title": "DB connections (idle)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "npgsql_db_client_connections_usage{state=\"idle\"}",
     "legendFormat": "idle"
    }
   ]
  }
 ]
}